name: CMake Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure CMake
      run: cmake -B _build
    - name: Build Project
      run: cmake --build _build
