name: CMake Build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Configure CMake
      run: cmake -B _build
    - name: Build Project
      run: cmake --build _build
